### ISSUE TITLE
samtools view: failed to open "" for reading: No such file or directory

### ISSUE THREAD

**Issue by Chi-Fa** [bcgsc/RAILS#13]
Hi,
I have two assemblies produced with PacBio by canu and 10X by supernova. Base on Rene's recent suggestion, I used the supernova assembly to scaffold and gapfill the canu assembly. I made overlapping sequence tiles of  2.5, 5, and 10 kbp from the supernova assembly. Then, the tiles were aligned to canu assembly by minimap2. Then, the sam file were converted to bam file. However, when I used the bam file to run cobbler/RAILS, it showed that :

` =>Reading bam: Wed Jul 31 04:11:07 EDT 2019
Parsing alignment file ▒BCo}▒{▒▒Eu▒▒KBHB ...
[E::hts_open_format] Failed to open file ▒
samtools view: failed to open "" for reading: No such file or directory

Redundant same contig combo linking:0
Same gap sequence fill:0 ` 

How can I solve the problem?

Thanks,
Chi-Fa

**Comment by lcoombe** [comment]
Hi @Chi-Fa,

Could you please include the names of all the files in your working directory (with `ls`), and the RAILS command you used? That will be very helpful to help you troubleshoot.

Thanks,
Lauren

**Comment by Chi-Fa** [comment]
Hi Lauren:
Thanks for the quick reply.
All files were put in the RAILS-master/bin/.  The bin folder include "cobbler.pl,  alignment.bam,  alignment.sam,  allTiles_supernova.fa,  canu_reference.fa RAILS,  runRAILSminimap.sh,  runRAILS.sh"

The command I used was `./RAILS -f canu_reference.fa -q allTiles_supernova.fa -s alignment.bam -p ~/samtools-1.8/samtools `

Chi-Fa

**Comment by lcoombe** [comment]
Thanks, @Chi-Fa - And I should have asked you before as well, but what version of RAILS are you using?

v1.4.1 requires that the long sequences and BAMs are listed in a file of filenames:
```
[lcoombe@lcoombe01 ~]$ RAILS 
Usage: /projects/btl/lcoombe/linuxbrew/bin/RAILS [v1.4.1]
-f  Assembled Sequences to further scaffold (Multi-Fasta format, required)
-q  File of filenames containing long Sequences queried (Multi-Fasta format, required)
-s  File of filenames containing full path to BAM file(s)
-p  Full path to samtools (known to work/tested with v1.8, required)
-d  Anchoring bases on contig edges (ie. minimum required alignment size on contigs, default -d 1000, optional)
-i  Minimum sequence identity fraction (0 to 1), default -i 0.9, optional
-t  LIST of names/header, long sequences to avoid using for merging/gap-filling scaffolds (optional)
-l  Minimum number of links to compute scaffold (default -l 1, optional)
-a  Maximum link ratio between two best contig pairs *higher values lead to least accurate scaffolding* (default -a 0.99, optional)
-g  Grace length (bp), default -g 1, optional
-b  Base name for your output files (optional)
-v  Runs in verbose mode (-v 1 = yes, default = no, optional)
IMPORTANT: the order of files in -q and -s MUST match!
```

**Comment by Chi-Fa** [comment]
Excuse me. I used v1.4.1 RAILS.  The command I used was `./RAILS -f canu_reference.fa -q allTiles_supernova.fa  -s ~/RAILS-master/bin/allTiles_supernova.bam -p ~/samtools-1.8/samtools`, but it showed 

> Can't write to canu_reference.fa.scaff_s-/home/chifa/RAILS-master/bin/allTiles_supernova.bam_q-allTiles_supernova.fa_d1000_i0.9_e1_l1_a0.99_g1_t_pid44188.log -- fatal

**Comment by lcoombe** [comment]
Hi @Chi-Fa,

Since you are using v1.4.1 for RAILS, you should input a file of filenames for `-q` and `-s`. Since you just have one file each for long sequences and alignments, just make separate files with 1 line each (long sequence filename and BAM file name, respectively). 
As for the other error, try setting `-b` - the basename of your files. I suspect that it is failing because you supplied a full path for the input fasta file, and it is trying to create a log file in directories that don't exist as a result.

Hope that helps!
Lauren

**Comment by Chi-Fa** [comment]
Hi, Lauren:

It can work. Many thanks for your help.

Best,
Chi-Fa

**Comment by lcoombe** [comment]
Great - I'm glad you got it working!
Thank you for your interest in RAILS!
