### ISSUE TITLE
bam file not produced

### ISSUE THREAD

**Issue by dcopetti** [bcgsc/RAILS#14]
Hello,
I was running RAILS to scaffold an assembly with ONT reads and I don't see a .bam file being produced.
I run it with this command:
`sh runRAILSminimap_190731.sh ../../Rabiosa_genome_v2.2.fa /home/copettid/public/Dario/Lolium/Oxford_Nanopore_data/batch_4_sequencig_190717/Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa 2000 0.90 250 5 ont /usr/local/bin/samtools &>stdout`
inside the shell script I edited the number of cores in minimap, but no bam file was generated. The beginning of the stdout says this:
```
Resolving ambiguous bases -Ns- in ../../Rabiosa_genome_v2.2.fa assembly using long sequences /home/copettid/public/Dario/Lolium/Oxford_Nanopore_data/batch_4_sequencig_190717/Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa
reformatting file ../../Rabiosa_genome_v2.2.fa
WARNING: MAKE SURE YOUR INPUT FASTA IS ONE SEQUENCE PER LINE WITH NO LINE BREAKS!
reformatting file /home/copettid/public/Dario/Lolium/Oxford_Nanopore_data/batch_4_sequencig_190717/Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa
Aligning long sequences /home/copettid/public/Dario/Lolium/Oxford_Nanopore_data/batch_4_sequencig_190717/Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa-formatted.fa to your contigs..
Running minimap2 with preset map-ont
runRAILSminimap_190731.sh: line 24: /home/copettid/public/Dario/Lolium/Oxford_Nanopore_data/batch_4_sequencig_190717/Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa_vs_../../Rabiosa_genome_v2.2.fa_gapfilling.bam: No such file or directory
[M::mm_idx_gen::81.339*1.59] collected minimizers
[M::mm_idx_gen::88.199*2.38] sorted minimizers
```
can it be because I have files with absolute paths in them?
Thanks,

Dario

**Comment by dcopetti** [comment]
update: I may have figured it out: with the files in the same folders, the alignment happens and the bam file is produced. The issue is that some new files are named by concatenating the input files, thus "/" would be added to the new file name.

**Comment by lcoombe** [comment]
Hi @dcopetti - Yes I think you are right about the naming causing issues. Try making soft links if neccessary, and re-running the script with all the necessary files in the current working directory.

For example, this name for the output BAM will cause you issues -- you could avoid by not specifying the full path to the files `Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa` and `Rabiosa_genome_v2.2.fa`:
```
/home/copettid/public/Dario/Lolium/Oxford_Nanopore_data/batch_4_sequencig_190717/Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa_vs_../../Rabiosa_genome_v2.2.fa_gapfilling.bam
```

Hope that helps!
Lauren
