### ISSUE TITLE
Polyploid analysis

### ISSUE THREAD

**Issue by trgibbons** [bcgsc/RAILS#15]
Hi René,

I'm currently using some ONT data to scaffold an allopolyploid plant genome assembly. The documentation for RAILS, LINKS, and Cobbler doesn't explicitly mention ploidy limitations, but I've found that it's often wise to check  :) 

(Sorry to spam you about polyploids both here and on the ARCS repo, but I thought there might be separate considerations)

Best,
Ted

**Comment by warrenlr** [comment]
Hello Ted, thank you for your interest in our tools.
Unfortunately I have no experience with polyploid genomes so can't comment much. In principle, the paradigms used for scaffolding, whether it uses a kmer based method (LINKS/ARKS) or direct alignment (cobbler/RAILS/ARCS) to anchor the sequences, should hold. Ideally, you would want to build a simulated dataset with a ground truth for testing.
