### ISSUE TITLE
no scaffolding - samtools issue?

### ISSUE THREAD

**Issue by dcopetti** [bcgsc/RAILS#16]
Hello,
I am trying to scaffold some Illumina scaffolds with ONT reads (>40 kb) with RAILS, but I get an error message that seems to point to the samtools version:
```
$ ./RAILS -f Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa_vs_Rabiosa_genome_v2.2.fa_2000_0.90_gapsFill-formatted.fa -s Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa_vs_Rabiosa_genome_v2.2.fa_scaffolding.fof -l 5 -g 250 -d 2000 -i 0.90 -b out_rails2 -q Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa-formatted.fof -p /home/copettid/bin/samtools-1.8/samtools

Running: ./RAILS [v1.4.1]
-f Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa_vs_Rabiosa_genome_v2.2.fa_2000_0.90_gapsFill-formatted.fa
-q Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa-formatted.fof
-s Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa_vs_Rabiosa_genome_v2.2.fa_scaffolding.fof
-d 2000
-i 0.90
-e 1
-l 5
-a 0.99
-g 250
-t

=>Reading bam: Wed Aug 14 18:38:19 CEST 2019
Parsing alignment file Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa_vs_Rabiosa_genome_v2.2.fa_scaffolding.bam...
Redundant same contig combo linking:0
Same gap sequence fill:0
done.
Contigs processed:
=>Scaffolding initiated: Wed Aug 14 18:49:54 CEST 2019
=>Scaffolding ended: Wed Aug 14 18:49:55 CEST 2019
Scaffolds layout in: out_rails2.scaffolds
=>Making fasta file: Wed Aug 14 18:49:56 CEST 2019
Scaffolds fasta in: out_rails2.scaffolds.fa
Empty arrayn -- maybe the scaffold merging step did not necessitate gap filling. It is also possible that your version of samtools is not supported. This script was tested with samtools v1.8. at ./RAILS line 220.
```

I got this when using the default samtools installation I had (1.9), and also when pointing RAILS to 1.8, the one you tested it with.
I am now assuming the problem is somewhere else: could you help me spot the issue?
The output files are empty:
```
-rw-r--r-- 1 copettid mpb    0 Aug 14 18:42 Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa_vs_Rabiosa_genome_v2.2.fa_scaffolding.bam.bampreprocessor.err.log68011565800937
-rw-r--r-- 1 copettid mpb    0 Aug 14 18:49 out_rails2.scaffolds
-rw-r--r-- 1 copettid mpb   78 Aug 14 18:49 out_rails2.pairing_issues
-rw-r--r-- 1 copettid mpb    0 Aug 14 18:49 out_rails2.pairing_distribution.csv
-rw-r--r-- 1 copettid mpb    0 Aug 14 18:49 out_rails2.scaffolds_GAPseqList.txt
-rw-r--r-- 1 copettid mpb    0 Aug 14 18:49 out_rails2.scaffolds.fa
-rw-r--r-- 1 copettid mpb 1.3K Aug 14 18:49 out_rails2.log
```
the bam file has a header that looks like this (when open with zcat):
```
BAM�8�@SQ       SN:wga1.1,18314 LN:18314
@SQ     SN:wga1.2,43129 LN:43129
@SQ     SN:wga1.3,59019 LN:59019
@SQ     SN:wga1.4,387   LN:387
@SQ     SN:wga1.5,22927 LN:22927
@SQ     SN:wga1.6,45475 LN:45475
@SQ     SN:wga1.7,85776 LN:85776
@SQ     SN:wga1.8,960   LN:960
@SQ     SN:wga1.9,17994 LN:17994
@SQ     SN:wga1.10,3060 LN:3060
```
can this be an issue?
Thanks,

Dario

**Comment by warrenlr** [comment]
Have you tried running the demo with the same version of 3rd party tool you ran with your experiment?  If the demo works as expected, I recommend that you map the reads using the pipeline provided (runRAILSminimap.sh) -- if you haven't already done so.

I assume that the: Rabiosa_b4_Guppy3.0.3_190718_40kb_q9.fa_vs_Rabiosa_genome_v2.2.fa_scaffolding.bam
file was generated by aligning the nanopore reads to the draft genome, please make sure the ONT flags were set in minimap2 (ie. -x map-ont) 

Also, looks like some of the params are too strict:

-d 2000
-i 0.90
-e 1
-l 5
-a 0.99


======

try to lower them and re-run:

-d 250
-i 0.8

to start, leave others at default and troubleshoot.

**Comment by dcopetti** [comment]
Hello,

I run the tests in the installation folder and I can get the scaffolding, also with the minimap pipeline (attached are the log files).

then from the working dir I run the minimap pipeline script with 50,000 ONT reads:
`sh runRAILSminimap_190731.sh Rabiosa_genome_v2.2.fa test.fa 1000 0.9 1 1 ont /home/copettid/bin/samtools-1.8/samtools`
and it works, in fact it scaffolds three sequences:
```
seq20699,5398
seq20851,2803
seq2969,4700
```

Now I am running just RAILS, but using the executable that is in the folder where I installed it (rather than the copy I made in the working dir). it will go overnight, can this be the issue with the samtools related error?


[RAILS_test_runs.txt](https://github.com/bcgsc/RAILS/files/3505743/RAILS_test_runs.txt)

**Comment by warrenlr** [comment]
good to know it is working.
There are many reasons why the results aren't stellar.

1. nanopore data itself, eg./ quality, sufficient+even coverage
2. could be that 90%+ sequence identity is still too high and your long reads have lower overall   accuracy
3. anchoring sequences of 1000bp is still too high, but I recommend you compute the nanopore read length distribution and see where the median length is (and or N50)
4. The -g (grace parameter) should be set to a value larger than 1. ONT reads have noise in 5'/3' that will be softclipped in the alignment (set it to 250)

the list of things that could affect scaffolding is long, but you should start with this & see.

**Comment by dcopetti** [comment]
Hello,

I am now using the full dataset, reads >40 kb, QV >9 (87.4% accuracy), the coverage is about 11x. The total assembly size is 4.9 Gb, N50 197 kb, N70 71 kb.

I did a run with default parameters
~/bin/RAILS/tarball/RAILS_v1.4.2/RAILS -f Rabiosa_genome_v2.2.fa -q longreads_fa.fof -s longreads_bam.fof -p /home/copettid/bin/samtools-1.8/samtools
and I got no scaffolding: see log file:
```
Running: /home/copettid/bin/RAILS/tarball/RAILS_v1.4.2/RAILS [v1.4.1]
-f Rabiosa_genome_v2.2.fa
-q longreads_fa.fof
-s longreads_bam.fof
-d 1000
-i 0.9
-e 1
-l 1
-a 0.99
-g 1
-t

=>Reading bam: Thu Sep  5 12:25:35 CEST 2019

=>Scaffolding initiated: Thu Sep  5 14:07:58 CEST 2019

===========PAIRED K-MER STATS===========
Total number of pairs extracted from -s longreads_bam.fof: 0
At least one sequence/pair missing from contigs: 0
Assembled pairs: 9245 (18490 sequences)
        Satisfied in distance/logic within contigs (i.e. -> <-, distance on target: 0
        Unsatisfied in distance within contigs (i.e. distance out-of-bounds): 159
        Unsatisfied pairing logic within contigs (i.e. illogical pairing ->->, <-<- or <-->): 4492
        ---
        Satisfied in distance/logic within a given contig pair (pre-scaffold): 0
        Unsatisfied in distance within a given contig pair (i.e. calculated distances out-of-bounds): 4594
        ---
Total satisfied: 0      unsatisfied: 9245

Breakdown by insert sizes:
============================================
=>Scaffolding ended: Thu Sep  5 14:08:18 CEST 2019
=>Making fasta file: Thu Sep  5 14:08:19 CEST 2019
```
One reason could be the -i threshold, and I am running it now with `-i 85`. 
I did other tests adding to the default command (in all combinations)
```
-d 10000
-i 0.9, 0.93, 0.87
-l 3, 5, 7
```
and I got no output: the log file says only
```
Running: /home/copettid/bin/RAILS/tarball/RAILS_v1.4.2/RAILS [v1.4.1]
-f Rabiosa_genome_v2.2.fa
-q longreads_fa.fof
-s longreads_bam.fof
-d 10000
-i 0.93
-e 1
-l 1
-a 0.99
-g 1
-t

=>Reading bam: Thu Sep  5 16:13:27 CEST 2019
```
Is this an issure related with memory? I am limited at 126 GB on the current machine.
Or, what else can it be that makes the runs fail (bottom) or no scaffolding to happen? 
Thanks

**Comment by warrenlr** [comment]
if you precede your command with "time", you should be able to see clearly how much RAM your process used and whether it crashed because of it
```
/usr/bin/time -v -o MYRUN_time.txt ~/bin/RAILS/tarball/RAILS_v1.4.2/RAILS -f Rabiosa_genome_v2.2.fa -q longreads_fa.fof -s longreads_bam.fof -p /home/copettid/bin/samtools-1.8/samtools 
```

Your reads might align, but it doesn't mean they align end-to-end without soft clipping -- this is important. The grace parameter (-g), which controls this, is set to -g 1, which is very stringent, expecting complete 5'-end alignments with a soft clip of a single base.  I would suggest setting to -g 250 or even 500.  I would also explore -i 0.7, 0.75, 0.8, 0.85

The other thing is your coverage, which is low.. and combined with an N50~200kbp there might not be many opportunities for further scaffolding; Although we saw some gains scaffolding 20Gb genome drafts with <5X raw uncorrected ONT reads.  @lcoombe could give you some pointers on those run parameters.

**Comment by dcopetti** [comment]
Thanks,
I will try your suggestions over the weekend.

So if 11x is too low for mapping-based scaffolding, do you think that k-mer based scaffolding (LINKS) may work then? I tried it on the same assembly with another set of long reads (N50 10 kb), and it gave little increase (but the new scaffolds were chimeric) and the memory usage was 300-800 GB. I am not sure I still can get a machine with 800 GB these days.
With 20% of the assembly in <6 kb sequences, I expect to have ONT reads that span a few of them, and scaffold with others, this is why I think it could be just a matter of parameter tuning. Or, if it still does not work, the genome may be too repetitive (!!) to find unique strings.
Any input is welcome!

**Comment by lcoombe** [comment]
Hi @dcopetti,
For our runs with <5X ONT reads with a 20Gb genome, we saw good results with d=500,1000 and i=0.85. Lowering the `i` parameter was necessary to get decent scaffolding with the ONT reads. As Rene mentioned, increasing the grace parameter is also quite important - I used g=500.
Good luck!

**Comment by dcopetti** [comment]
Yep, the issue should be in the headers of the long reads.
To avoid repeating the alignment (and make it faster, on a cluster), I split the pipeline and then run only RAILS. I used the -formatted.fa genome, but not the formatted.fa reads.
This could be the reason why RAILS was not finding connections in the bam file, I am re-running the alignment now.

**Comment by dcopetti** [comment]
update:
when running the pipeline (all default), everything works fine and I get a little scaffolding:
```
Total number of pairs extracted from -s /home/copettid/public/Dario/Lolium/Oxford_Nanopore_data/Rabiosa_ONT_Guppy303_all_190807_40kb_q9a.fa_vs_Rabiosa_genome_v2.2.fa_scaffolding.fof: 0
At least one sequence/pair missing from contigs: 0
Assembled pairs: 738 (1476 sequences)
        Satisfied in distance/logic within contigs (i.e. -> <-, distance on target: 0
        Unsatisfied in distance within contigs (i.e. distance out-of-bounds): 0
        Unsatisfied pairing logic within contigs (i.e. illogical pairing ->->, <-<- or <-->): 0
        ---
        Satisfied in distance/logic within a given contig pair (pre-scaffold): 738
        Unsatisfied in distance within a given contig pair (i.e. calculated distances out-of-bounds): 0
        ---
Total satisfied: 738    unsatisfied: 0
```
N50 and N70 values increase of 1 kb, because of the 738 pairs I guess.

Then, to avoid re-running the file formatting and the alignments (takes >1 day vs 3-4 h of RAILS only), I run only RAILS as
`/usr/bin/time -v -o run_time6.txt ~/bin/RAILS/tarball/RAILS_v1.4.2/RAILS -f Rabiosa_genome_v2.2.fa-formatted.fa -q Rabiosa_ONT_Guppy303_all_190807_40kb_q9a.fa-formatted.fof -s Rabiosa_ONT_Guppy303_all_190807_40kb_q9a.fa_vs_Rabiosa_genome_v2.2.fa_scaffolding.fof -p /home/copettid/bin/samtools-1.8/samtools -d 1000 -i 0.85 -l 1 -g 250 -b 3_85_1_250`
with a parameter sweep, but I get no scaffolding, with the same stats as above (N50 and N70 smaller than the initial assembly).
These are some of the stats:
```
$ grep "led pairs" *log
10_70_1_500.log:Assembled pairs: 32389 (64778 sequences)
3_85_1_250.log:Assembled pairs: 13121 (26242 sequences)
4_80_1_250.log:Assembled pairs: 26158 (52316 sequences)
5_75_1_250.log:Assembled pairs: 28675 (57350 sequences)
6_70_1_250.log:Assembled pairs: 29379 (58758 sequences)
7_85_1_500.log:Assembled pairs: 14360 (28720 sequences)
8_80_1_500.log:Assembled pairs: 28738 (57476 sequences)
9_75_1_500.log:Assembled pairs: 31597 (63194 sequences)
$ grep "unsatisf" *log
10_70_1_500.log:Total satisfied: 31849  unsatisfied: 540
3_85_1_250.log:Total satisfied: 12880   unsatisfied: 241
4_80_1_250.log:Total satisfied: 25749   unsatisfied: 409
5_75_1_250.log:Total satisfied: 28222   unsatisfied: 453
6_70_1_250.log:Total satisfied: 28915   unsatisfied: 464
7_85_1_500.log:Total satisfied: 14088   unsatisfied: 272
8_80_1_500.log:Total satisfied: 28261   unsatisfied: 477
9_75_1_500.log:Total satisfied: 31069   unsatisfied: 528
```
so, formatted assembly, formatted reads, and bam file match I guess.
Is the -s file correct? *_scaffolding.fof 
It points to `Rabiosa_ONT_Guppy303_all_190807_40kb_q9a.fa_vs_Rabiosa_genome_v2.2.fa_scaffolding.bam`

I will run again the whole pipeline with different settings, to see if going the long way we get some scaffolding. However, it is a pity to have to repeat all the alignments (and cobbler step) when nothing changes.

**Comment by warrenlr** [comment]
Did you run RAILS independently on each readFile:bamFile combo? I ask because you have multiple log files but should have a SINGLE log. 

Note: You only need to run RAILS once, by putting all reads in -q and all bams in -s, in order such that there should be 1:1 read(-q):bam(-s) equivalent. This step (RAILS or cobbler) should run on a single machine.

**Comment by dcopetti** [comment]
No, the different log files are for different settings of a RAILS run: my input is 1 assembly multifasta (formatted by the .sh script), 1 long reads multifasta (formatted by the .sh script), 1 bam file.

**Comment by warrenlr** [comment]
could you paste the result of : 
```
grep "merges" *log
```

**Comment by dcopetti** [comment]
shoot: too late, I deleted the files already. I will start one now, same parameters as above
