### ISSUE TITLE
Are the versions listed for bwa, minimap2, and samtools *exact* or minimum requirements?

### ISSUE THREAD

**Issue by SchwarzEM** [bcgsc/RAILS#17]
Your documentation lists the following programs as being prerequisites for RAILS to work (with version numbers given in parentheses):

bwa (version 0.7.15-r1140) or minimap2 (version 2.15-r905)
samtools (version 1.8)

Are these requirements *exact*, or merely minimum version numbers?  In other words, is there any reason to assume that RAILS could not work equally well with (say) minimap2 version 2.17-r941 and samtools version 1.9?

**Comment by warrenlr** [comment]
these are the only versions I tested.
I guess they are minimum requirements..
