### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Johnsonzcode** [bcgsc/RAILS#36]
Hi @andrewjpage,

After running the code, I think it might be good if :
- explain the Samtools version in README(I can't run with samtools lastest version.)
- explain `-g` parameters in detail
- if I set `RAILS PATH` in RAILS/versions/RAILS_v1.5.1/runRAILSminimapSTREAM.sh line 10, line 28, 32, 36, 52, 56, 60 shoud be `cobbler.pl` or `RAILS` not `./*`

**Comment by warrenlr** [comment]
done. Thanks for the suggestions and your interest in cobbler/RAILS
