### ISSUE TITLE
samtools hard-coded to a gsc-specific path

### ISSUE THREAD

**Issue by dy7t** [bcgsc/RAILS#8]
Both cobbler.pl & RAILS define SAMPATH to be "/gsc/btl/linuxbrew/bin/samtools"

The readme doesn't mention that it needs to be changed or that RAILS depends on samtools (any particular version?)

Without a valid samtools, the tests fail with:
  Empty arrayn -- maybe the scaffold merging step did not necessitate
  gap filling. at /group/bioinfo/apps/apps/RAILS_v1.4/RAILS line 215.
  RAILS process terminated.

Consider checking that a valid samtools is present and print clear error message if its missing.

This bug was opened and then closed as fixed, but nothing seems to have changed.

I was using version 1.4

**Comment by mmokrejs** [comment]
Rene,
  please drop the "../" from bin/runRAILS.sh as well. Also the line `export PATH=/gsc/btl/linuxbrew/bin:$PATH`. These are awkward. Please instruct users in Readme.md to provide samtools and your scripts via PATH. That is enough.

**Comment by mmokrejs** [comment]
The hardcoded `PATHs` are still present in `bin/*.sh` files. Also cmdline options to pass number of threads would be helpful.

**Comment by warrenlr** [comment]
done.
